import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated from the `docs/` directory structure.
 *
 * Ordering comes from the `sidebar_position` in each page's frontmatter and the
 * `position` in each folder's `_category_.json`, so adding a page is a matter of
 * dropping the file in the right folder with the right position.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
